-- MySQL Script generated by MySQL Workbench
-- Thu Dec 26 11:36:14 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tienda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tienda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tienda` DEFAULT CHARACTER SET latin1 ;
USE `tienda` ;

-- -----------------------------------------------------
-- Table `tienda`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(64) NULL,
  `descripcion` VARCHAR(64) NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(128) NULL,
  `descripcion` VARCHAR(256) NULL,
  `precio` DECIMAL(10,0) NULL,
  `stock` INT(10) NULL,
  `importancia` INT(10) NULL,
  `imagen` VARCHAR(20) NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_producto_categoria1_idx` (`id_categoria` ASC),
  CONSTRAINT `fk_producto_categoria1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `tienda`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`usuario` (
  `id_usuario` VARCHAR(20) NOT NULL,
  `clave` VARCHAR(20) NULL,
  `nombres` VARCHAR(64) NULL,
  `paterno` VARCHAR(64) NULL,
  `materno` VARCHAR(64) NULL,
  `correo` VARCHAR(64) NULL,
  `direccion` VARCHAR(128) NULL,
  `telefono` VARCHAR(32) NULL,
  `estado` CHAR(1) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `estado` CHAR(1) NULL,
  `total` DECIMAL(10,2) NULL,
  `id_usuario` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_pedido_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_pedido_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `tienda`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`detalle_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`detalle_pedido` (
  `id_detalle_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NOT NULL,
  `id_pedido` INT NOT NULL,
  `precio` DECIMAL(10,2) NULL,
  `cantidad` INT(10) NULL,
  PRIMARY KEY (`id_detalle_pedido`, `id_producto`, `id_pedido`),
  INDEX `fk_detalle_pedido_producto1_idx` (`id_producto` ASC),
  INDEX `fk_detalle_pedido_pedido1_idx` (`id_pedido` ASC),
  CONSTRAINT `fk_detalle_pedido_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `tienda`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_pedido_pedido1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `tienda`.`pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`rol` (
  `rol_nombre` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`rol_nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`usuario_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`usuario_rol` (
  `id_usuario` VARCHAR(20) NOT NULL,
  `rol_nombre` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `rol_nombre`),
  INDEX `fk_usuario_rol_rol1_idx` (`rol_nombre` ASC),
  CONSTRAINT `fk_usuario_rol_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `tienda`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_rol_rol1`
    FOREIGN KEY (`rol_nombre`)
    REFERENCES `tienda`.`rol` (`rol_nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`aviso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`aviso` (
  `id_aviso` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(64) NULL,
  `fecha_inicio` DATETIME NULL,
  `fecha_fin` DATETIME NULL,
  `estado` CHAR(1) NULL,
  `id_usuario` VARCHAR(20) NULL,
  PRIMARY KEY (`id_aviso`),
  INDEX `fk_aviso_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_aviso_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `tienda`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
